# -*- coding: utf-8 -*-
"""AudioSet 527 类 (AST 打标模型) 标签表

EN_LIST 按模型 config.id2label 的索引顺序排列 (0..526), 与网络输出 logits 一一对应,
由 MIT/ast-finetuned-audioset-10-10-0.4593 的 config.json 生成, 保证与权重一致。
CN_MAP 为中文译名, 未收录的类回退英文; label_cn() 负责查询。
"""

EN_LIST = [
    "Speech",
    "Male speech, man speaking",
    "Female speech, woman speaking",
    "Child speech, kid speaking",
    "Conversation",
    "Narration, monologue",
    "Babbling",
    "Speech synthesizer",
    "Shout",
    "Bellow",
    "Whoop",
    "Yell",
    "Battle cry",
    "Children shouting",
    "Screaming",
    "Whispering",
    "Laughter",
    "Baby laughter",
    "Giggle",
    "Snicker",
    "Belly laugh",
    "Chuckle, chortle",
    "Crying, sobbing",
    "Baby cry, infant cry",
    "Whimper",
    "Wail, moan",
    "Sigh",
    "Singing",
    "Choir",
    "Yodeling",
    "Chant",
    "Mantra",
    "Male singing",
    "Female singing",
    "Child singing",
    "Synthetic singing",
    "Rapping",
    "Humming",
    "Groan",
    "Grunt",
    "Whistling",
    "Breathing",
    "Wheeze",
    "Snoring",
    "Gasp",
    "Pant",
    "Snort",
    "Cough",
    "Throat clearing",
    "Sneeze",
    "Sniff",
    "Run",
    "Shuffle",
    "Walk, footsteps",
    "Chewing, mastication",
    "Biting",
    "Gargling",
    "Stomach rumble",
    "Burping, eructation",
    "Hiccup",
    "Fart",
    "Hands",
    "Finger snapping",
    "Clapping",
    "Heart sounds, heartbeat",
    "Heart murmur",
    "Cheering",
    "Applause",
    "Chatter",
    "Crowd",
    "Hubbub, speech noise, speech babble",
    "Children playing",
    "Animal",
    "Domestic animals, pets",
    "Dog",
    "Bark",
    "Yip",
    "Howl",
    "Bow-wow",
    "Growling",
    "Whimper (dog)",
    "Cat",
    "Purr",
    "Meow",
    "Hiss",
    "Caterwaul",
    "Livestock, farm animals, working animals",
    "Horse",
    "Clip-clop",
    "Neigh, whinny",
    "Cattle, bovinae",
    "Moo",
    "Cowbell",
    "Pig",
    "Oink",
    "Goat",
    "Bleat",
    "Sheep",
    "Fowl",
    "Chicken, rooster",
    "Cluck",
    "Crowing, cock-a-doodle-doo",
    "Turkey",
    "Gobble",
    "Duck",
    "Quack",
    "Goose",
    "Honk",
    "Wild animals",
    "Roaring cats (lions, tigers)",
    "Roar",
    "Bird",
    "Bird vocalization, bird call, bird song",
    "Chirp, tweet",
    "Squawk",
    "Pigeon, dove",
    "Coo",
    "Crow",
    "Caw",
    "Owl",
    "Hoot",
    "Bird flight, flapping wings",
    "Canidae, dogs, wolves",
    "Rodents, rats, mice",
    "Mouse",
    "Patter",
    "Insect",
    "Cricket",
    "Mosquito",
    "Fly, housefly",
    "Buzz",
    "Bee, wasp, etc.",
    "Frog",
    "Croak",
    "Snake",
    "Rattle",
    "Whale vocalization",
    "Music",
    "Musical instrument",
    "Plucked string instrument",
    "Guitar",
    "Electric guitar",
    "Bass guitar",
    "Acoustic guitar",
    "Steel guitar, slide guitar",
    "Tapping (guitar technique)",
    "Strum",
    "Banjo",
    "Sitar",
    "Mandolin",
    "Zither",
    "Ukulele",
    "Keyboard (musical)",
    "Piano",
    "Electric piano",
    "Organ",
    "Electronic organ",
    "Hammond organ",
    "Synthesizer",
    "Sampler",
    "Harpsichord",
    "Percussion",
    "Drum kit",
    "Drum machine",
    "Drum",
    "Snare drum",
    "Rimshot",
    "Drum roll",
    "Bass drum",
    "Timpani",
    "Tabla",
    "Cymbal",
    "Hi-hat",
    "Wood block",
    "Tambourine",
    "Rattle (instrument)",
    "Maraca",
    "Gong",
    "Tubular bells",
    "Mallet percussion",
    "Marimba, xylophone",
    "Glockenspiel",
    "Vibraphone",
    "Steelpan",
    "Orchestra",
    "Brass instrument",
    "French horn",
    "Trumpet",
    "Trombone",
    "Bowed string instrument",
    "String section",
    "Violin, fiddle",
    "Pizzicato",
    "Cello",
    "Double bass",
    "Wind instrument, woodwind instrument",
    "Flute",
    "Saxophone",
    "Clarinet",
    "Harp",
    "Bell",
    "Church bell",
    "Jingle bell",
    "Bicycle bell",
    "Tuning fork",
    "Chime",
    "Wind chime",
    "Change ringing (campanology)",
    "Harmonica",
    "Accordion",
    "Bagpipes",
    "Didgeridoo",
    "Shofar",
    "Theremin",
    "Singing bowl",
    "Scratching (performance technique)",
    "Pop music",
    "Hip hop music",
    "Beatboxing",
    "Rock music",
    "Heavy metal",
    "Punk rock",
    "Grunge",
    "Progressive rock",
    "Rock and roll",
    "Psychedelic rock",
    "Rhythm and blues",
    "Soul music",
    "Reggae",
    "Country",
    "Swing music",
    "Bluegrass",
    "Funk",
    "Folk music",
    "Middle Eastern music",
    "Jazz",
    "Disco",
    "Classical music",
    "Opera",
    "Electronic music",
    "House music",
    "Techno",
    "Dubstep",
    "Drum and bass",
    "Electronica",
    "Electronic dance music",
    "Ambient music",
    "Trance music",
    "Music of Latin America",
    "Salsa music",
    "Flamenco",
    "Blues",
    "Music for children",
    "New-age music",
    "Vocal music",
    "A capella",
    "Music of Africa",
    "Afrobeat",
    "Christian music",
    "Gospel music",
    "Music of Asia",
    "Carnatic music",
    "Music of Bollywood",
    "Ska",
    "Traditional music",
    "Independent music",
    "Song",
    "Background music",
    "Theme music",
    "Jingle (music)",
    "Soundtrack music",
    "Lullaby",
    "Video game music",
    "Christmas music",
    "Dance music",
    "Wedding music",
    "Happy music",
    "Funny music",
    "Sad music",
    "Tender music",
    "Exciting music",
    "Angry music",
    "Scary music",
    "Wind",
    "Rustling leaves",
    "Wind noise (microphone)",
    "Thunderstorm",
    "Thunder",
    "Water",
    "Rain",
    "Raindrop",
    "Rain on surface",
    "Stream",
    "Waterfall",
    "Ocean",
    "Waves, surf",
    "Steam",
    "Gurgling",
    "Fire",
    "Crackle",
    "Vehicle",
    "Boat, Water vehicle",
    "Sailboat, sailing ship",
    "Rowboat, canoe, kayak",
    "Motorboat, speedboat",
    "Ship",
    "Motor vehicle (road)",
    "Car",
    "Vehicle horn, car horn, honking",
    "Toot",
    "Car alarm",
    "Power windows, electric windows",
    "Skidding",
    "Tire squeal",
    "Car passing by",
    "Race car, auto racing",
    "Truck",
    "Air brake",
    "Air horn, truck horn",
    "Reversing beeps",
    "Ice cream truck, ice cream van",
    "Bus",
    "Emergency vehicle",
    "Police car (siren)",
    "Ambulance (siren)",
    "Fire engine, fire truck (siren)",
    "Motorcycle",
    "Traffic noise, roadway noise",
    "Rail transport",
    "Train",
    "Train whistle",
    "Train horn",
    "Railroad car, train wagon",
    "Train wheels squealing",
    "Subway, metro, underground",
    "Aircraft",
    "Aircraft engine",
    "Jet engine",
    "Propeller, airscrew",
    "Helicopter",
    "Fixed-wing aircraft, airplane",
    "Bicycle",
    "Skateboard",
    "Engine",
    "Light engine (high frequency)",
    "Dental drill, dentist's drill",
    "Lawn mower",
    "Chainsaw",
    "Medium engine (mid frequency)",
    "Heavy engine (low frequency)",
    "Engine knocking",
    "Engine starting",
    "Idling",
    "Accelerating, revving, vroom",
    "Door",
    "Doorbell",
    "Ding-dong",
    "Sliding door",
    "Slam",
    "Knock",
    "Tap",
    "Squeak",
    "Cupboard open or close",
    "Drawer open or close",
    "Dishes, pots, and pans",
    "Cutlery, silverware",
    "Chopping (food)",
    "Frying (food)",
    "Microwave oven",
    "Blender",
    "Water tap, faucet",
    "Sink (filling or washing)",
    "Bathtub (filling or washing)",
    "Hair dryer",
    "Toilet flush",
    "Toothbrush",
    "Electric toothbrush",
    "Vacuum cleaner",
    "Zipper (clothing)",
    "Keys jangling",
    "Coin (dropping)",
    "Scissors",
    "Electric shaver, electric razor",
    "Shuffling cards",
    "Typing",
    "Typewriter",
    "Computer keyboard",
    "Writing",
    "Alarm",
    "Telephone",
    "Telephone bell ringing",
    "Ringtone",
    "Telephone dialing, DTMF",
    "Dial tone",
    "Busy signal",
    "Alarm clock",
    "Siren",
    "Civil defense siren",
    "Buzzer",
    "Smoke detector, smoke alarm",
    "Fire alarm",
    "Foghorn",
    "Whistle",
    "Steam whistle",
    "Mechanisms",
    "Ratchet, pawl",
    "Clock",
    "Tick",
    "Tick-tock",
    "Gears",
    "Pulleys",
    "Sewing machine",
    "Mechanical fan",
    "Air conditioning",
    "Cash register",
    "Printer",
    "Camera",
    "Single-lens reflex camera",
    "Tools",
    "Hammer",
    "Jackhammer",
    "Sawing",
    "Filing (rasp)",
    "Sanding",
    "Power tool",
    "Drill",
    "Explosion",
    "Gunshot, gunfire",
    "Machine gun",
    "Fusillade",
    "Artillery fire",
    "Cap gun",
    "Fireworks",
    "Firecracker",
    "Burst, pop",
    "Eruption",
    "Boom",
    "Wood",
    "Chop",
    "Splinter",
    "Crack",
    "Glass",
    "Chink, clink",
    "Shatter",
    "Liquid",
    "Splash, splatter",
    "Slosh",
    "Squish",
    "Drip",
    "Pour",
    "Trickle, dribble",
    "Gush",
    "Fill (with liquid)",
    "Spray",
    "Pump (liquid)",
    "Stir",
    "Boiling",
    "Sonar",
    "Arrow",
    "Whoosh, swoosh, swish",
    "Thump, thud",
    "Thunk",
    "Electronic tuner",
    "Effects unit",
    "Chorus effect",
    "Basketball bounce",
    "Bang",
    "Slap, smack",
    "Whack, thwack",
    "Smash, crash",
    "Breaking",
    "Bouncing",
    "Whip",
    "Flap",
    "Scratch",
    "Scrape",
    "Rub",
    "Roll",
    "Crushing",
    "Crumpling, crinkling",
    "Tearing",
    "Beep, bleep",
    "Ping",
    "Ding",
    "Clang",
    "Squeal",
    "Creak",
    "Rustle",
    "Whir",
    "Clatter",
    "Sizzle",
    "Clicking",
    "Clickety-clack",
    "Rumble",
    "Plop",
    "Jingle, tinkle",
    "Hum",
    "Zing",
    "Boing",
    "Crunch",
    "Silence",
    "Sine wave",
    "Harmonic",
    "Chirp tone",
    "Sound effect",
    "Pulse",
    "Inside, small room",
    "Inside, large room or hall",
    "Inside, public space",
    "Outside, urban or manmade",
    "Outside, rural or natural",
    "Reverberation",
    "Echo",
    "Noise",
    "Environmental noise",
    "Static",
    "Mains hum",
    "Distortion",
    "Sidetone",
    "Cacophony",
    "White noise",
    "Pink noise",
    "Throbbing",
    "Vibration",
    "Television",
    "Radio",
    "Field recording",
]

# 中文译名: 英文类名 -> 中文 (未收录的类回退英文原文)
CN_MAP = {
    # 人声与人体
    "Speech": "语音", "Male speech, man speaking": "男声说话",
    "Female speech, woman speaking": "女声说话", "Child speech, kid speaking": "儿童说话",
    "Conversation": "对话", "Narration, monologue": "旁白独白", "Babbling": "咿呀学语",
    "Speech synthesizer": "语音合成", "Shout": "喊叫", "Bellow": "吼叫", "Whoop": "欢呼",
    "Yell": "大叫", "Battle cry": "呐喊", "Children shouting": "儿童喊叫",
    "Screaming": "尖叫", "Whispering": "耳语", "Laughter": "笑声",
    "Baby laughter": "婴儿笑声", "Giggle": "咯咯笑", "Snicker": "偷笑",
    "Belly laugh": "捧腹大笑", "Chuckle, chortle": "轻笑", "Crying, sobbing": "哭泣",
    "Baby cry, infant cry": "婴儿啼哭", "Whimper": "呜咽", "Wail, moan": "哀号",
    "Sigh": "叹气", "Singing": "歌唱", "Choir": "合唱", "Yodeling": "约德尔唱法",
    "Chant": "吟唱", "Mantra": "经文吟诵", "Male singing": "男声歌唱",
    "Female singing": "女声歌唱", "Child singing": "童声歌唱",
    "Synthetic singing": "合成歌声", "Rapping": "说唱", "Humming": "哼唱",
    "Groan": "呻吟", "Grunt": "咕哝", "Whistling": "吹口哨", "Breathing": "呼吸声",
    "Wheeze": "喘息", "Snoring": "打鼾", "Gasp": "喘气", "Pant": "急促呼吸",
    "Snort": "鼻息", "Cough": "咳嗽", "Throat clearing": "清嗓", "Sneeze": "打喷嚏",
    "Sniff": "吸鼻", "Run": "跑步", "Shuffle": "拖步", "Walk, footsteps": "脚步",
    "Chewing, mastication": "咀嚼", "Biting": "咬", "Gargling": "漱口",
    "Stomach rumble": "肠鸣", "Burping, eructation": "打嗝", "Hiccup": "打呃",
    "Fart": "放屁", "Hands": "手部动作", "Finger snapping": "打响指",
    "Clapping": "拍手", "Heart sounds, heartbeat": "心跳", "Heart murmur": "心脏杂音",
    "Cheering": "欢呼", "Applause": "掌声", "Chatter": "闲聊", "Crowd": "人群",
    "Hubbub, speech noise, speech babble": "嘈杂人声", "Children playing": "儿童玩耍",
    # 动物
    "Animal": "动物", "Domestic animals, pets": "家养动物", "Dog": "狗", "Bark": "犬吠",
    "Yip": "狗尖叫", "Howl": "嚎叫", "Bow-wow": "汪汪叫", "Growling": "低吼",
    "Whimper (dog)": "狗呜咽", "Cat": "猫", "Purr": "猫呼噜", "Meow": "猫叫",
    "Hiss": "嘶嘶声", "Caterwaul": "猫叫春",
    "Livestock, farm animals, working animals": "家畜", "Horse": "马",
    "Clip-clop": "马蹄声", "Neigh, whinny": "马嘶", "Cattle, bovinae": "牛",
    "Moo": "牛叫", "Cowbell": "牛铃", "Pig": "猪", "Oink": "猪叫", "Goat": "山羊",
    "Bleat": "羊叫", "Sheep": "绵羊", "Fowl": "家禽", "Chicken, rooster": "鸡",
    "Cluck": "咯咯叫", "Crowing, cock-a-doodle-doo": "公鸡打鸣", "Turkey": "火鸡",
    "Gobble": "火鸡叫", "Duck": "鸭", "Quack": "鸭叫", "Goose": "鹅", "Honk": "鹅叫",
    "Wild animals": "野生动物", "Roaring cats (lions, tigers)": "狮虎咆哮",
    "Roar": "咆哮", "Bird": "鸟", "Bird vocalization, bird call, bird song": "鸟鸣",
    "Chirp, tweet": "鸟啁啾", "Squawk": "鸟尖叫", "Pigeon, dove": "鸽子",
    "Coo": "鸽咕咕", "Crow": "乌鸦", "Caw": "鸦叫", "Owl": "猫头鹰",
    "Hoot": "猫头鹰叫", "Bird flight, flapping wings": "振翅",
    "Canidae, dogs, wolves": "犬科", "Rodents, rats, mice": "啮齿动物",
    "Mouse": "老鼠", "Patter": "轻快脚步声", "Insect": "昆虫", "Cricket": "蟋蟀",
    "Mosquito": "蚊子", "Fly, housefly": "苍蝇", "Buzz": "嗡嗡声",
    "Bee, wasp, etc.": "蜜蜂黄蜂", "Frog": "青蛙", "Croak": "蛙鸣", "Snake": "蛇",
    "Rattle": "响尾蛇声", "Whale vocalization": "鲸叫",
    # 乐器
    "Music": "音乐", "Musical instrument": "乐器", "Plucked string instrument": "拨弦乐器",
    "Guitar": "吉他", "Electric guitar": "电吉他", "Bass guitar": "贝斯",
    "Acoustic guitar": "原声吉他", "Steel guitar, slide guitar": "钢弦吉他",
    "Tapping (guitar technique)": "吉他点弦", "Strum": "扫弦", "Banjo": "班卓琴",
    "Sitar": "西塔琴", "Mandolin": "曼陀林", "Zither": "古筝", "Ukulele": "尤克里里",
    "Keyboard (musical)": "键盘乐器", "Piano": "钢琴", "Electric piano": "电钢琴",
    "Organ": "风琴", "Electronic organ": "电子琴", "Hammond organ": "哈蒙德风琴",
    "Synthesizer": "合成器", "Sampler": "采样器", "Harpsichord": "大键琴",
    "Percussion": "打击乐", "Drum kit": "架子鼓", "Drum machine": "鼓机", "Drum": "鼓",
    "Snare drum": "军鼓", "Rimshot": "边击", "Drum roll": "滚奏", "Bass drum": "大鼓",
    "Timpani": "定音鼓", "Tabla": "塔布拉鼓", "Cymbal": "镲", "Hi-hat": "踩镲",
    "Wood block": "木鱼", "Tambourine": "铃鼓", "Rattle (instrument)": "摇响器",
    "Maraca": "沙锤", "Gong": "锣", "Tubular bells": "管钟",
    "Mallet percussion": "键盘打击乐", "Marimba, xylophone": "马林巴木琴",
    "Glockenspiel": "钟琴", "Vibraphone": "颤音琴", "Steelpan": "钢鼓",
    "Orchestra": "管弦乐", "Brass instrument": "铜管乐器", "French horn": "圆号",
    "Trumpet": "小号", "Trombone": "长号", "Bowed string instrument": "弓弦乐器",
    "String section": "弦乐组", "Violin, fiddle": "小提琴", "Pizzicato": "拨奏",
    "Cello": "大提琴", "Double bass": "低音提琴",
    "Wind instrument, woodwind instrument": "管乐器", "Flute": "长笛",
    "Saxophone": "萨克斯", "Clarinet": "单簧管", "Harp": "竖琴", "Bell": "铃",
    "Church bell": "教堂钟", "Jingle bell": "铃铛", "Bicycle bell": "车铃",
    "Tuning fork": "音叉", "Chime": "钟鸣", "Wind chime": "风铃",
    "Change ringing (campanology)": "教堂钟乐", "Harmonica": "口琴",
    "Accordion": "手风琴", "Bagpipes": "风笛", "Didgeridoo": "迪吉里杜管",
    "Shofar": "羊角号", "Theremin": "特雷门琴", "Singing bowl": "颂钵",
    "Scratching (performance technique)": "搓碟",
    # 音乐风格
    "Pop music": "流行乐", "Hip hop music": "嘻哈乐", "Beatboxing": "口技",
    "Rock music": "摇滚乐", "Heavy metal": "重金属", "Punk rock": "朋克",
    "Grunge": "垃圾摇滚", "Progressive rock": "前卫摇滚", "Rock and roll": "摇滚",
    "Psychedelic rock": "迷幻摇滚", "Rhythm and blues": "节奏布鲁斯",
    "Soul music": "灵魂乐", "Reggae": "雷鬼", "Country": "乡村音乐",
    "Swing music": "摇摆乐", "Bluegrass": "蓝草", "Funk": "放克", "Folk music": "民谣",
    "Middle Eastern music": "中东音乐", "Jazz": "爵士", "Disco": "迪斯科",
    "Classical music": "古典乐", "Opera": "歌剧", "Electronic music": "电子乐",
    "House music": "浩室", "Techno": "科技舞曲", "Dubstep": "回响贝斯",
    "Drum and bass": "鼓打贝斯", "Electronica": "电子音乐",
    "Electronic dance music": "电子舞曲", "Ambient music": "氛围乐",
    "Trance music": "迷幻舞曲", "Music of Latin America": "拉美音乐",
    "Salsa music": "萨尔萨", "Flamenco": "弗拉门戈", "Blues": "布鲁斯",
    "Music for children": "儿童音乐", "New-age music": "新世纪音乐",
    "Vocal music": "声乐", "A capella": "无伴奏合唱", "Music of Africa": "非洲音乐",
    "Afrobeat": "非洲节拍", "Christian music": "基督教音乐",
    "Gospel music": "福音音乐", "Music of Asia": "亚洲音乐",
    "Carnatic music": "卡纳提克音乐", "Music of Bollywood": "宝莱坞音乐",
    "Ska": "斯卡", "Traditional music": "传统音乐", "Independent music": "独立音乐",
    "Song": "歌曲", "Background music": "背景音乐", "Theme music": "主题曲",
    "Jingle (music)": "短曲", "Soundtrack music": "原声配乐", "Lullaby": "摇篮曲",
    "Video game music": "游戏音乐", "Christmas music": "圣诞音乐",
    "Dance music": "舞曲", "Wedding music": "婚礼音乐", "Happy music": "欢快音乐",
    "Funny music": "诙谐音乐", "Sad music": "悲伤音乐", "Tender music": "轻柔音乐",
    "Exciting music": "激昂音乐", "Angry music": "愤怒音乐", "Scary music": "惊悚音乐",
    # 自然
    "Wind": "风", "Rustling leaves": "树叶沙沙", "Wind noise (microphone)": "风噪",
    "Thunderstorm": "雷暴", "Thunder": "雷", "Water": "水", "Rain": "雨",
    "Raindrop": "雨滴", "Rain on surface": "雨打物体", "Stream": "溪流",
    "Waterfall": "瀑布", "Ocean": "海洋", "Waves, surf": "海浪", "Steam": "蒸汽",
    "Gurgling": "汩汩声", "Fire": "火", "Crackle": "噼啪声",
    # 交通
    "Vehicle": "交通工具", "Boat, Water vehicle": "船", "Sailboat, sailing ship": "帆船",
    "Rowboat, canoe, kayak": "划艇", "Motorboat, speedboat": "摩托艇", "Ship": "轮船",
    "Motor vehicle (road)": "机动车", "Car": "汽车",
    "Vehicle horn, car horn, honking": "汽车喇叭", "Toot": "短促喇叭",
    "Car alarm": "汽车防盗器", "Power windows, electric windows": "电动车窗",
    "Skidding": "刹车打滑", "Tire squeal": "轮胎尖叫", "Car passing by": "汽车驶过",
    "Race car, auto racing": "赛车", "Truck": "卡车", "Air brake": "气刹",
    "Air horn, truck horn": "气喇叭", "Reversing beeps": "倒车提示音",
    "Ice cream truck, ice cream van": "冰淇淋车", "Bus": "公交车",
    "Emergency vehicle": "应急车辆", "Police car (siren)": "警车鸣笛",
    "Ambulance (siren)": "救护车鸣笛", "Fire engine, fire truck (siren)": "消防车鸣笛",
    "Motorcycle": "摩托车", "Traffic noise, roadway noise": "交通噪声",
    "Rail transport": "铁路", "Train": "火车", "Train whistle": "火车汽笛",
    "Train horn": "火车喇叭", "Railroad car, train wagon": "车厢",
    "Train wheels squealing": "车轮摩擦", "Subway, metro, underground": "地铁",
    "Aircraft": "航空器", "Aircraft engine": "航空发动机", "Jet engine": "喷气发动机",
    "Propeller, airscrew": "螺旋桨", "Helicopter": "直升机",
    "Fixed-wing aircraft, airplane": "固定翼飞机", "Bicycle": "自行车",
    "Skateboard": "滑板", "Engine": "发动机", "Light engine (high frequency)": "高频引擎",
    "Dental drill, dentist's drill": "牙钻", "Lawn mower": "割草机", "Chainsaw": "电锯",
    "Medium engine (mid frequency)": "中频引擎",
    "Heavy engine (low frequency)": "低频引擎", "Engine knocking": "引擎爆震",
    "Engine starting": "引擎启动", "Idling": "怠速",
    "Accelerating, revving, vroom": "加速轰鸣",
    # 居家
    "Door": "门", "Doorbell": "门铃", "Ding-dong": "叮咚", "Sliding door": "推拉门",
    "Slam": "摔门", "Knock": "敲门", "Tap": "轻敲", "Squeak": "吱吱声",
    "Cupboard open or close": "柜门开合", "Drawer open or close": "抽屉开合",
    "Dishes, pots, and pans": "锅碗瓢盆", "Cutlery, silverware": "餐具",
    "Chopping (food)": "切菜", "Frying (food)": "煎炸", "Microwave oven": "微波炉",
    "Blender": "搅拌机", "Water tap, faucet": "水龙头",
    "Sink (filling or washing)": "水槽", "Bathtub (filling or washing)": "浴缸",
    "Hair dryer": "吹风机", "Toilet flush": "冲马桶", "Toothbrush": "牙刷",
    "Electric toothbrush": "电动牙刷", "Vacuum cleaner": "吸尘器",
    "Zipper (clothing)": "拉链", "Keys jangling": "钥匙串响",
    "Coin (dropping)": "硬币掉落", "Scissors": "剪刀",
    "Electric shaver, electric razor": "电动剃须刀", "Shuffling cards": "洗牌",
    "Typing": "打字", "Typewriter": "打字机", "Computer keyboard": "电脑键盘",
    "Writing": "书写",
    # 警报与信号
    "Alarm": "警报", "Telephone": "电话", "Telephone bell ringing": "电话铃",
    "Ringtone": "铃声", "Telephone dialing, DTMF": "电话拨号",
    "Dial tone": "拨号音", "Busy signal": "忙音", "Alarm clock": "闹钟",
    "Siren": "警笛", "Civil defense siren": "防空警报", "Buzzer": "蜂鸣器",
    "Smoke detector, smoke alarm": "烟雾报警", "Fire alarm": "火警",
    "Foghorn": "雾号", "Whistle": "哨声", "Steam whistle": "汽笛",
    # 机械
    "Mechanisms": "机械", "Ratchet, pawl": "棘轮", "Clock": "时钟", "Tick": "滴答",
    "Tick-tock": "摆钟滴答", "Gears": "齿轮", "Pulleys": "滑轮",
    "Sewing machine": "缝纫机", "Mechanical fan": "机械风扇",
    "Air conditioning": "空调", "Cash register": "收银机", "Printer": "打印机",
    "Camera": "照相机", "Single-lens reflex camera": "单反相机", "Tools": "工具",
    "Hammer": "锤子", "Jackhammer": "风镐", "Sawing": "锯", "Filing (rasp)": "锉磨",
    "Sanding": "打磨", "Power tool": "电动工具", "Drill": "电钻",
    # 爆炸与射击
    "Explosion": "爆炸", "Gunshot, gunfire": "枪声", "Machine gun": "机枪",
    "Fusillade": "连射", "Artillery fire": "炮击", "Cap gun": "玩具枪",
    "Fireworks": "烟花", "Firecracker": "鞭炮", "Burst, pop": "爆裂",
    "Eruption": "喷发", "Boom": "轰鸣",
    # 材质与碰撞
    "Wood": "木头", "Chop": "劈砍", "Splinter": "碎裂", "Crack": "开裂",
    "Glass": "玻璃", "Chink, clink": "叮当", "Shatter": "破碎", "Liquid": "液体",
    "Splash, splatter": "溅水", "Slosh": "晃荡", "Squish": "挤压", "Drip": "滴水",
    "Pour": "倾倒", "Trickle, dribble": "细流", "Gush": "涌出",
    "Fill (with liquid)": "注水", "Spray": "喷洒", "Pump (liquid)": "泵",
    "Stir": "搅拌", "Boiling": "沸腾",
    # 其他音效与环境
    "Sonar": "声呐", "Arrow": "箭", "Whoosh, swoosh, swish": "呼啸",
    "Thump, thud": "闷响", "Thunk": "钝响", "Electronic tuner": "调音器",
    "Effects unit": "效果器", "Chorus effect": "合唱效果",
    "Basketball bounce": "篮球弹跳", "Bang": "砰", "Slap, smack": "拍打",
    "Whack, thwack": "重击", "Smash, crash": "撞击", "Breaking": "断裂",
    "Bouncing": "弹跳", "Whip": "鞭打", "Flap": "拍打", "Scratch": "抓擦",
    "Scrape": "刮擦", "Rub": "摩擦", "Roll": "滚动", "Crushing": "碾碎",
    "Crumpling, crinkling": "揉皱", "Tearing": "撕裂", "Beep, bleep": "哔声",
    "Ping": "叮", "Ding": "叮当", "Clang": "铿锵", "Squeal": "尖啸",
    "Creak": "吱嘎", "Rustle": "沙沙", "Whir": "呼呼", "Clatter": "咔哒",
    "Sizzle": "滋滋声",
    "Clicking": "咔嗒", "Clickety-clack": "咔嗒咔嗒", "Rumble": "隆隆",
    "Plop": "扑通", "Jingle, tinkle": "叮铃", "Hum": "嗡鸣", "Zing": "锐响",
    "Boing": "弹响", "Crunch": "嘎吱", "Silence": "静音", "Sine wave": "正弦波",
    "Harmonic": "谐波", "Chirp tone": "啁啾音", "Sound effect": "音效",
    "Pulse": "脉冲", "Inside, small room": "小房间混响",
    "Inside, large room or hall": "大厅混响", "Inside, public space": "公共空间",
    "Outside, urban or manmade": "城市户外", "Outside, rural or natural": "自然户外",
    "Reverberation": "混响", "Echo": "回声", "Noise": "噪声",
    "Environmental noise": "环境噪声", "Static": "静电噪声",
    "Mains hum": "电源嗡声", "Distortion": "失真", "Sidetone": "侧音",
    "Cacophony": "刺耳杂音", "White noise": "白噪声", "Pink noise": "粉红噪声",
    "Throbbing": "脉动", "Vibration": "振动", "Television": "电视",
    "Radio": "收音机", "Field recording": "现场录音",
}


def label_cn(name):
    """英文类名 -> 中文译名 (缺失时回退英文原文)"""
    return CN_MAP.get(name, name)
